regions:
  - global
  #- us-east-1
  #- us-east-2
  #- us-west-1
  #- us-west-2
  #- af-south-1
  #- ap-east-1
  #- ap-south-1
  #- ap-northeast-1
  - ap-northeast-2
  #- ap-northeast-3
  #- ap-southeast-1
  #- ap-southeast-2
  #- ap-southeast-3
  #- ca-central-1
  #- eu-central-1
  #- eu-west-1

account-blocklist:
  - 1234567890

resource-types:
  targets: []
  excludes: []

accounts:
  790840705158: {}
